### ISSUE TITLE
Removing redundant 1.

### ISSUE THREAD

**Issue by trigaten** [benchmark-urbanism/remark-bibtex#1]
I am using this plugin to generate output like:

Ref A:[^1] Ref B:[^2]

[^1]: 1\. Harris CR, Millman KJ, van der Walt SJ, Gommers R, Virtanen P, Cournapeau D, et al. Array programming with NumPy. Nature \[Internet]. 2020 Sep;585(7825):357–62. Available from: http\://www\.nature.com/articles/s41586-020-2649-2

[^2]: 1\. Wasserman S, Faust K. Social Network Analysis. Cambridge: Cambridge University Press; 1994.&#x20;

Why are there redundant 1s here (1. 1. , 2. 1. )?

**Comment by songololo** [comment]
My apologies for the delayed response. I'm no longer developing this package, however, you might find that [`rehype-citation`](https://github.com/timlrx/rehype-citation) could work for your purposes?
